### ISSUE TITLE
Add Configure= in module.info

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic_dot_module#1]

**Comment by andrewmallis** [comment]
Oh! now I get it once I see the solution in #3!
I am more of a problem -> solution guy. Trying to adapt to this Jeopardy format.

**Comment by RobLoach** [comment]
Oh I just enjoy cryptic story titles. :ghost: :rabbit: :thiago:

**Comment by soniktrooth** [comment]
This is fixed
