### ISSUE TITLE
Clarify path to module configuration

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic_dot_module#2]
Our module configuration is at ``/kalastatic`` which is nice but it does not follow standard drupal patterns. Module configuration typically lives off ``/admin/config/``.

Suggest we live instead at ``/admin/config/kalastatic`` which will give us a bonus link in the drupal menu system.

Additionally, I think this would provide us a link from the ``/admin/modules`` to the config page.

As it stands, users don't have a clue where to go sort of sifting through the module code. The configuration section of our README file does not provide  path!

**Comment by soniktrooth** [comment]
#3 is merged but this issue still stands

**Comment by soniktrooth** [comment]
I managed to win this with a hook_menu_local_tasks_alter so we can have tabs that aren't relative to the `MENU_DEFAULT_LOCAL_TASK`. So config now lives at `admin/config/kalastatic` where as prototype and styleguide are still living at `kalastatic/prototype` and `kalastatic/styleguide` respectively.

**Comment by soniktrooth** [comment]
@RobLoach do you wanna give this a quick look over and make sure it's all good from a Drupal POV. Don't want to give the reviewers anything to gripe over.

**Comment by RobLoach** [comment]
Submitted a couple of PRs as follow ups. Looks pretty good to me. May be good to have a real-world test on EECS.

**Comment by RobLoach** [comment]
Closing this, as things have been merged.
